repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/datarootsio/databooks
    rev: 1.3.10
    hooks:
    -   id: databooks-meta
    -   id: databooks-assert
