on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: pip install .
      - run: python -m unittest
